spring.datasource.url=jdbc:postgresql://localhost:5432/revista                                     
spring.datasource.username=postgres
spring.datasource.password=andres170496

# Specify the DBMS
spring.jpa.database = POSTGRESQL
# Show or not log for each sql query
spring.jpa.show-sql = true

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto= update

# Naming strategy
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager)
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8088
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB


